version: "3.8"

name: first-docker-project
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./src
        target: /usr/src/app/src
